-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 21:56:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_lista_produtos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_lista_produtos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_lista_produtos` DEFAULT CHARACTER SET utf8 ;
USE `db_lista_produtos` ;

-- -----------------------------------------------------
-- Table `db_lista_produtos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lista_produtos`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(255) NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_lista_produtos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_lista_produtos`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `descricao` TEXT NULL,
  `preco` DOUBLE NULL,
  `imagem` VARCHAR(255) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
